'DataFrame' object has no attribute 'ball'Traceback (most recent call last):
  File "D:\workspace\Distributed-Replays\backend\tasks\celery_tasks.py", line 110, in parse_replay_task
    analysis_manager = analyze_replay_file(fn, output)  # type: ReplayGame
  File "c:\users\david windows\appdata\local\programs\python\python36\lib\site-packages\carball\decompile_replays.py", line 76, in analyze_replay_file
    analysis.create_analysis()
  File "c:\users\david windows\appdata\local\programs\python\python36\lib\site-packages\carball\analysis\analysis_manager.py", line 53, in create_analysis
    self.perform_full_analysis(self.game, self.protobuf_game, player_map, data_frame, kickoff_frames)
  File "c:\users\david windows\appdata\local\programs\python\python36\lib\site-packages\carball\analysis\analysis_manager.py", line 62, in perform_full_analysis
    self.calculate_hit_stats(game, proto_game, player_map, data_frame, kickoff_frames)
  File "c:\users\david windows\appdata\local\programs\python\python36\lib\site-packages\carball\analysis\analysis_manager.py", line 116, in calculate_hit_stats
    hits = BaseHit.get_hits_from_game(game, proto_game, self.id_creator, data_frame)
  File "c:\users\david windows\appdata\local\programs\python\python36\lib\site-packages\carball\analysis\hit_detection\base_hit.py", line 32, in get_hits_from_game
    hit_frame_numbers = BaseHit.get_hit_frame_numbers_by_ball_ang_vel(data_frame)
  File "c:\users\david windows\appdata\local\programs\python\python36\lib\site-packages\carball\analysis\hit_detection\base_hit.py", line 132, in get_hit_frame_numbers_by_ball_ang_vel
    ball_ang_vels = data_frame.ball.loc[:, ['ang_vel_x', 'ang_vel_y', 'ang_vel_z']]
  File "c:\users\david windows\appdata\local\programs\python\python36\lib\site-packages\pandas\core\generic.py", line 4376, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'ball'
